### ISSUE TITLE
url 地址栏显示问题

### ISSUE THREAD

**Issue by mrli20182018** [zhongshaofa/layuimini#12]
![image](https://user-images.githubusercontent.com/42336683/73182641-607bb600-4154-11ea-9876-9f673fd25af5.png)

url地址里跳转的页面或者接口地址 不想显示在url地址栏里 能隐藏吗?
layuimini.config 文件在哪里 没有找了

**Comment by zhongshaofa** [comment]
在layuimini.config 修改urlHashLocation为false
