### ISSUE TITLE
左侧菜单加载慢

### ISSUE THREAD

**Issue by melin** [zhongshaofa/layuimini#15]
左侧菜单加载慢，中间区域内容出来了，菜单内容还看不见
![image](https://user-images.githubusercontent.com/1145830/75523319-c060c780-5a46-11ea-8c38-c64ce3927684.png)

**Comment by zhongshaofa** [comment]
返回的数据格式不对，打开控制台进行调试

**Comment by melin** [comment]
能够加载的出来，就是显示比较慢。

钟绍发 <notifications@github.com> 于2020年2月29日周六 下午5:52写道：

**Comment by zhongshaofa** [comment]
目前v2版加了初始化动漫，只有全部初始化完才显示
