### ISSUE TITLE
表单验证问题

### ISSUE THREAD

**Issue by try3** [zhongshaofa/layuimini#19]
发现所有的layui框架的表单验证都和官方一致。非常不友好！
比如，手机非必填，但是格式填错了，必须提交的时候才能检测出来，如果这样的有几个，比如邮箱。那会非常的不友好，提交一次才能检测出来，而且是一个个检测。
没有失去焦点验证，是否有优化计划？

**Comment by zhongshaofa** [comment]
目前没有计划去深度做插件
