### ISSUE TITLE
layui-body 高度不正常

### ISSUE THREAD

**Issue by h0730303779** [zhongshaofa/layuimini#20]
layui-body 高度异常 
iframe 页面内可以上下滑动

**Comment by zhongshaofa** [comment]
具体描述，或者附上演示视频

**Comment by h0730303779** [comment]
> 具体描述，或者附上演示视频

http://layuimini.99php.cn/iframe/v2/index.html#/page/layer.html
滚轮上下 就知道了
这样会导致我内部  card height: 100vh;   会出现滚动条

**Comment by zhongshaofa** [comment]
已修改，你再测试一下

**Comment by h0730303779** [comment]
> 已修改，你再测试一下

谢谢 能告知下你改那个样式吗.. 我改了半天没改成功

**Comment by zhongshaofa** [comment]
请查看提交记录[https://github.com/zhongshaofa/layuimini/commit/3ecd327ebb7685de401aa3d0626e7607db9a0b82](url)
