### ISSUE TITLE
单页面版发现的问题

### ISSUE THREAD

**Issue by 1099438829** [zhongshaofa/layuimini#3]
page/upload.html 1、2 行引入修改为

![微信图片_20190904215824](https://user-images.githubusercontent.com/2869110/64261462-27516800-cf5f-11e9-9d3b-727b1b2d2215.png)

<link rel="stylesheet" href="./lib/layui-v2.5.4/css/layui.css" media="all">
<link rel="stylesheet" href="./lib/jq-module/zyupload/zyupload-1.0.0.min.css" media="all">

53 54行 修改为
![微信图片_20190904215904](https://user-images.githubusercontent.com/2869110/64261521-3c2dfb80-cf5f-11e9-90f8-651d52ba901a.png)

<script src="./lib/jquery-3.4.1/jquery-3.4.1.min.js" charset="utf-8"></script>
<script src="./lib/jq-module/zyupload/zyupload-1.0.0.min.js" charset="utf-8"></script>

form-step.html
第一行 
![微信图片_20190904215946](https://user-images.githubusercontent.com/2869110/64261577-55cf4300-cf5f-11e9-99bf-f9c3950ca891.png)

<link rel="stylesheet" href="./lib/lay-module/step-lay/step.css" media="all">

缺少文件

![image](https://user-images.githubusercontent.com/2869110/64261630-65e72280-cf5f-11e9-82ce-f7d15dda8e91.png)

index.html
108行 修改
![image](https://user-images.githubusercontent.com/2869110/64261702-80210080-cf5f-11e9-9852-673c2780aa53.png)
 window.location = 'page/login-1.html';

**Comment by zhongshaofa** [comment]
描述不清晰
