### ISSUE TITLE
menuChildOpen这个参数设置了没用

### ISSUE THREAD

**Issue by GeoWong** [zhongshaofa/layuimini#32]
menuChildOpen这个参数设置了没用，下面源码中根本没用到
/**
         * 单模块
         * @param menuList 菜单数据
         * @param menuChildOpen 是否默认展开
         */
        renderSingleModule: function (menuList, **menuChildOpen**) {
            menuList = menuList || [];
            var leftMenuHtml = '',
                **childOpenClass** = '',
                leftMenuCheckDefault = 'layui-this';
            var me = this ;
            if (**menuChildOpen**) **childOpenClass** = ' layui-nav-itemed';
            leftMenuHtml = this.renderLeftMenu(menuList) ;
            $('.layui-layout-body').addClass('layuimini-single-module'); //单模块标识
            $('.layuimini-header-menu').remove();
            $('.layuimini-menu-left').html(leftMenuHtml);
            element.init();
        }

**Comment by zhongshaofa** [comment]
重构菜单缩放之后产生的问题，迟点会修复的

**Comment by zhongshaofa** [comment]
已修复
