### ISSUE TITLE
table的几点建议

### ISSUE THREAD

**Issue by liyang-live** [zhongshaofa/layuimini#35]
1、table能否点新增在下面新增空行，可以直接录入 保存
2、table新增的空行能否在单元格内输入首字母检索,如下效果
![WechatIMG8](https://user-images.githubusercontent.com/22491465/80341929-e6171b00-8895-11ea-9e8b-bd732201c6c4.jpeg)

**Comment by zhongshaofa** [comment]
目前都是使用layui的table功能
