### ISSUE TITLE
弹出层使用miniTab失效

### ISSUE THREAD

**Issue by C-XianSen** [zhongshaofa/layuimini#36]
弹出层使用时 ele需要为parent.parent.layui.element
![image](https://user-images.githubusercontent.com/37855864/81469929-7cdec280-921a-11ea-8a09-940b9541b0f8.png)

**Comment by zhongshaofa** [comment]
什么样的场景需要在弹出层内使用`miniTab`

**Comment by C-XianSen** [comment]
> 什么样的场景需要在弹出层内使用`miniTab`

在一个 ’Table‘ 中的 ‘toolbar’ 下打开的弹出层去使用文档提到的两个方式都没反应
![image](https://user-images.githubusercontent.com/37855864/81516326-110b6f80-936a-11ea-9a85-b7fa9aae1fed.png)

**Comment by zhongshaofa** [comment]
我这边看不到图片, 如果你的弹出层打开的是个iframe,  必然会失效,  如果只是个页面是可以的。打开iframe的话, 需要自行再改造多一个监听,  使用`parent.parent.layui`试一下

**Comment by C-XianSen** [comment]
> 我这边看不到图片, 如果你的弹出层打开的是个iframe, 必然会失效, 如果只是个页面是可以的。打开iframe的话, 需要自行再改造多一个监听, 使用`parent.parent.layui`试一下

没错，就是这样（我就是追加多一层 'parent' 去执行）

**Comment by zhongshaofa** [comment]
因为我框架本身不建议再多层iframe内使用, 这个层级可以是无限层, 没必要都去做兼容, 也没有什么太大的意义
