### ISSUE TITLE
找不到 miniAdmin.js文件

### ISSUE THREAD

**Issue by ody5sey** [zhongshaofa/layuimini#43]
我用django做后台处理，由于django对静态文件的处理机制导致找不到 miniAdmin.js

![image](https://user-images.githubusercontent.com/60533474/82923375-6fad2c00-9fad-11ea-81c7-e3a1865d58ac.png)

**Comment by zhongshaofa** [comment]
这个你应该是去看`django`的文档, 与我框架没有关系的

**Comment by zhongshaofa** [comment]
去看他的静态文件处理机制

**Comment by ody5sey** [comment]
我想知道怎么指定miniAdmin.js的绝对路径，因为layuimini他是从相对路径读取的导致找不到文件
