### ISSUE TITLE
layui版本升级到2.6.7最新版后，菜单箭头位置不正常，希望大佬能适配

### ISSUE THREAD

**Issue by shuohao** [zhongshaofa/layuimini#70]
正常位置箭头
![image](https://user-images.githubusercontent.com/4637107/119124307-19a98200-ba63-11eb-91a0-3b8eaa87ad0f.png)

异常位置箭头
![image](https://user-images.githubusercontent.com/4637107/119124390-2fb74280-ba63-11eb-9147-e47ee89519ab.png)

**Comment by Jzow** [comment]
Hello, you can use v2.6.3. , layuimini in v2.6.7 does not support it

**Comment by evergrand** [comment]
删除layuimini.css行683-736的代码

**Comment by zf8848** [comment]
在 layuimini.css 172 行：

**Comment by xuzihan1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zf8848** [comment]
layuimini.css 172 行  .layuimini-menu-left .layui-nav .layui-nav-more {
    right: 15px;
    top:20px;    <---- 新增的
}
layui 2.7.6 测试可以。

**Comment by joyol** [comment]
3楼的会导致字体和图标的距离变小
6楼的没问题
还有个问题展开后,箭头图标会偏移
715行:.layuimini-menu-left .layui-nav-itemed > a > .layui-nav-more,.layuimini-menu-left-zoom .layui-nav-itemed > a > .layui-nav-more 
将text-align: center; 改为 text-align: right;
