### ISSUE TITLE
将layui.js更新至2.7版本之后会出现菜单渲染不上的问题

### ISSUE THREAD

**Issue by zimomo** [zhongshaofa/layuimini#86]
![image](https://user-images.githubusercontent.com/33084492/226625220-ddd9bc08-8939-4700-85bc-64e9ec3096ac.png)
，这里看起来渲染的不是html而是一段字符串导致无法正常展示

**Comment by xuzihan1** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Billy-666** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zimomo** [comment]
楼下有解决方案
