### ISSUE TITLE
表单点击提交后怎么跳转到其他页面?

### ISSUE THREAD

**Issue by tangchao1992** [zhongshaofa/layuimini#9]
你好,layuimini很好用很漂亮
目前遇到的问题:
单页面版本中在提交了表单后,ajax的success回调中加了layer.msg怎么跳到新的页面?
当前写法:
```
$.ajax({
   ...
   success:function(data){
        layer.msg(data.msg,1000,function(){
              window.location.href = 'page/user-list.html';
        })
   }
})
```
只有地址栏的地址变了,但页面没有跳转?

**Comment by luckytangl** [comment]
$.ajax({
   ...
   success:function(data){
        layer.msg(data.msg,1000,function(){
              window.location = 'page/user-list.html';
        })
   }
})

**Comment by luckytangl** [comment]
> 你好,layuimini很好用很漂亮
> 目前遇到的问题:
> 单页面版本中在提交了表单后,ajax的success回调中加了layer.msg怎么跳到新的页面?
> 当前写法:
> 
> ```
> $.ajax({
>    ...
>    success:function(data){
>         layer.msg(data.msg,1000,function(){
>               window.location.href = 'page/user-list.html';
>         })
>    }
> })
> ```
> 
> 只有地址栏的地址变了,但页面没有跳转?

$.ajax({
...
success:function(data){
layer.msg(data.msg,1000,function(){
window.location = 'page/user-list.html';
})
}
})

**Comment by luckytangl** [comment]
$.ajax({
...
success:function(data){
layer.msg(data.msg,1000,function(){
window.location = 'page/user-list.html';
})
}
})

**Comment by 805131398** [comment]
好的 谢谢&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"luckytangl"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 下午3:39
收件人:&nbsp;"zhongshaofa/layuimini"<layuimini@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [zhongshaofa/layuimini] 表单点击提交后怎么跳转到其他页面? (#9)




$.ajax({
 ...
 success:function(data){
 layer.msg(data.msg,1000,function(){
 window.location = 'page/user-list.html';
 })
 }
 })

**Comment by tangchao1992** [comment]
> $.ajax({
> ...
> success:function(data){
> layer.msg(data.msg,1000,function(){
> window.location = 'page/user-list.html';
> })
> }
> })

你好,谢谢你的回复,但还是不能实现跳转,除了```<a ref="javascript:;" data-content-href="page/new.html" data-title="跳转">跳转</a>```这种a标签的点击跳转外,js中怎么实现跳转?

**Comment by tangchao1992** [comment]
这样就可以跳转了,重新初始化页面
```
layuimini.initPageTitle(href, title);
layuimini.initConten(href);
layuimini.initDevice();
```

**Comment by zhongshaofa** [comment]
v2版新增跳转方法：`miniPage.hashChange(href);`
